# Form implementation generated from reading ui file 'tools/gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 211)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(650, 484))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.select_output_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_output_folder.setObjectName("select_output_folder")
        self.gridLayout.addWidget(self.select_output_folder, 1, 2, 1, 1)
        self.select_input_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_input_folder.setObjectName("select_input_folder")
        self.gridLayout.addWidget(self.select_input_folder, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.input_folder = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_folder.setObjectName("input_folder")
        self.gridLayout.addWidget(self.input_folder, 0, 1, 1, 1)
        self.config_file = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.config_file.setObjectName("config_file")
        self.gridLayout.addWidget(self.config_file, 2, 1, 1, 1)
        self.select_file_with_config = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_file_with_config.setObjectName("select_file_with_config")
        self.gridLayout.addWidget(self.select_file_with_config, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.output_folder = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_folder.setObjectName("output_folder")
        self.gridLayout.addWidget(self.output_folder, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 4, 2, 1, 1)
        self.log_label = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.log_label.setObjectName("log_label")
        self.gridLayout.addWidget(self.log_label, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input folder"))
        self.select_output_folder.setText(_translate("MainWindow", "Select"))
        self.select_input_folder.setText(_translate("MainWindow", "Select"))
        self.label_3.setText(_translate("MainWindow", "File with config"))
        self.select_file_with_config.setText(_translate("MainWindow", "Select"))
        self.label_2.setText(_translate("MainWindow", "Output folder"))
        self.submit.setText(_translate("MainWindow", "Protect"))
        self.log_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
